import Link from "next/link";
import { Metadata } from "next";
import { SuccessContainer } from "./successStyles";
import { Suspense } from "react";
import SuccessCheckoutInfo from "@/components/SuccessCheckoutInfo";

export const metadata: Metadata = {
  title: "Compra efetuada | Ignite Shop",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function Success() {
  return (
    <SuccessContainer>
      <h1>Compra efetuada!</h1>
      <Suspense>
        <SuccessCheckoutInfo />
      </Suspense>
      <Link href="/">Voltar ao catálogo</Link>
    </SuccessContainer>
  );
}
