import { getProducts } from "@/service/Products";
import Slider from "@/components/Slider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | Ignite Shop",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getProducts();

  return <Slider products={products} />;
}
